project_id = "pgywvtphfidouakypdno"

[functions.admin-get-users]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.admin-get-login-logs]
verify_jwt = false

[functions.admin-get-reports]
verify_jwt = false

[functions.daily-blog-generator]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.ping-sitemap]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.sitemap-index]
verify_jwt = false

[functions.sitemap-main]
verify_jwt = false

[functions.sitemap-category]
verify_jwt = false

[functions.sitemap-static]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.indexnow]
verify_jwt = false

[functions.amp-question]
verify_jwt = false

[functions.sitemap-amp]
verify_jwt = false

[functions.quiz-question-ssr]
verify_jwt = false

[functions.sitemap-category-history]
verify_jwt = false

[functions.sitemap-category-science]
verify_jwt = false

[functions.sitemap-category-geography]
verify_jwt = false

[functions.sitemap-category-literature]
verify_jwt = false

[functions.sitemap-category-entertainment]
verify_jwt = false

[functions.sitemap-category-sports]
verify_jwt = false

[functions.sitemap-category-technology]
verify_jwt = false

[functions.sitemap-category-general-knowledge]
verify_jwt = false
