project_id = "pgywvtphfidouakypdno"

[functions.admin-get-users]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.admin-get-login-logs]
verify_jwt = false

[functions.admin-get-reports]
verify_jwt = false

[functions.daily-blog-generator]
verify_jwt = false

[functions.ping-sitemap]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.indexnow]
verify_jwt = false

[functions.amp-question]
verify_jwt = false

[functions.quiz-question-ssr]
verify_jwt = false

[functions.sitemap-main]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.admin-create-quiz-question]
verify_jwt = false

[functions.backfill-explanations]
verify_jwt = false
