// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in CuizIN player's profile: username, display name, and current gem/points balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("username, display_name, points, gems_balance, profile_picture, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-quiz-stats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";
var get_my_quiz_stats_default = defineTool2({
  name: "get_my_quiz_stats",
  title: "Get my quiz stats",
  description: "Summarize the signed-in player's quiz performance: total questions attempted, correct answers, accuracy, and points earned. Optionally limit to a recent window of days.",
  inputSchema: {
    days: z.number().int().positive().describe("Only count answers from the last N days. Omit for all-time stats.").optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("quiz_answers").select("correct, points_earned, answered_at").eq("user_id", ctx.getUserId());
    if (days) {
      const since = new Date(Date.now() - days * 24 * 60 * 60 * 1e3).toISOString();
      query = query.gte("answered_at", since);
    }
    const { data, error } = await query.limit(1e4);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const attempted = rows.length;
    const correct = rows.filter((r) => r.correct).length;
    const pointsEarned = rows.reduce((sum, r) => sum + (r.points_earned ?? 0), 0);
    const stats = {
      window: days ? `last ${days} days` : "all time",
      attempted,
      correct,
      incorrect: attempted - correct,
      accuracyPct: attempted ? Math.round(correct / attempted * 1e3) / 10 : 0,
      pointsEarned
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List quiz categories",
  description: "List the available CuizIN quiz categories with the number of questions in each.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("quiz_questions").select("category").limit(1e4);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      if (!row.category) continue;
      counts.set(row.category, (counts.get(row.category) ?? 0) + 1);
    }
    const categories = Array.from(counts, ([category, questionCount]) => ({
      category,
      questionCount
    })).sort((a, b) => b.questionCount - a.questionCount);
    return {
      content: [{ type: "text", text: JSON.stringify(categories) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/get-quiz-questions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_quiz_questions_default = defineTool4({
  name: "get_quiz_questions",
  title: "Get quiz questions",
  description: "Fetch CuizIN quiz questions with their answer options. Correct answers are never returned. Optionally filter by category and difficulty.",
  inputSchema: {
    category: z2.string().describe("Filter by category name (see list_categories).").optional(),
    difficulty: z2.string().describe("Filter by difficulty, e.g. easy, medium, hard.").optional(),
    limit: z2.number().int().positive().describe("Max questions to return (default 10).").optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ category, difficulty, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("quiz_questions").select("id, question, options, category, difficulty, image_url, points, question_type");
    if (category) query = query.eq("category", category);
    if (difficulty) query = query.eq("difficulty", difficulty);
    const { data, error } = await query.limit(Math.min(limit ?? 10, 50));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const questions = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(questions) }],
      structuredContent: { questions }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool5({
  name: "get_leaderboard",
  title: "Get monthly leaderboard",
  description: "Get the CuizIN monthly points leaderboard. Defaults to the current month; pass a month like '2026-07'.",
  inputSchema: {
    month: z3.string().describe("Month in YYYY-MM format. Omit for the current month.").optional(),
    limit: z3.number().int().positive().describe("Number of top players to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ month, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    const args = { _limit: Math.min(limit ?? 20, 100) };
    if (month) args._month = month;
    const { data, error } = await supabase.rpc("get_monthly_leaderboard", args);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const leaderboard = (data ?? []).map((r, i) => ({
      rank: i + 1,
      username: r.username,
      displayName: r.display_name,
      points: r.points
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(leaderboard) }],
      structuredContent: { leaderboard }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pgywvtphfidouakypdno";
var mcp_default = defineMcp({
  name: "cuizin-mcp",
  title: "CuizIN MCP",
  version: "0.1.0",
  instructions: "Tools for CuizIN, a points-based quiz game. Use get_my_profile and get_my_quiz_stats for the signed-in player's own data, list_categories and get_quiz_questions to browse quiz content (correct answers are never exposed), and get_leaderboard for monthly rankings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_quiz_stats_default, list_categories_default, get_quiz_questions_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
