
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jthvngwrojfceavebgsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0aHZuZ3dyb2pmY2VhdmViZ3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTAzNDcsImV4cCI6MjA1NzUyNjM0N30.McoNTVy6kkgRo_ElGbgPnqvuYqOq2zLtX8gOvTRLI3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with any type to avoid type errors
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
