// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnrvmphfyxgwweqjoomp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucnZtcGhmeXhnd3dlcWpvb21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODAyMjEsImV4cCI6MjA1NzQ1NjIyMX0.xQv2ZSqeKImsSMnP6kXquooJdJtSCWU4dYjJURK34XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define a type that includes all valid table names
type TableName = keyof Database['public']['Tables'];

// Create a singleton instance of the Supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Check if there's a valid Supabase session
export const hasValidSession = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      console.error('Error checking session:', error);
      return false;
    }
    return !!data.session;
  } catch (err) {
    console.error('Failed to check session status:', err);
    return false;
  }
};

// Create or get a user in Supabase auth
export const ensureUserExists = async (username: string, email?: string, password?: string) => {
  try {
    // First check if user exists in profiles
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('username', username)
      .maybeSingle();
      
    if (profile) {
      console.log('User already exists in profiles:', profile);
      return { success: true, profile };
    }
    
    // If no existing profile, create one with a random ID since we don't have auth
    const userId = crypto.randomUUID();
    const { error: insertError } = await supabase
      .from('profiles')
      .insert({
        id: userId,
        username: username,
        points: parseInt(localStorage.getItem('user_points') || '0'),
      });
      
    if (insertError) {
      console.error('Error creating profile:', insertError);
      return { success: false, error: insertError };
    }
    
    console.log('Created new profile for:', username);
    return { success: true, profile: { id: userId, username } };
  } catch (err) {
    console.error('Failed to ensure user exists:', err);
    return { success: false, error: err };
  }
};

// Helper function to synchronize localStorage data with Supabase
export const syncDataWithSupabase = async (
  tableName: string, 
  localStorageKey: string, 
  transform?: (item: any) => any
) => {
  try {
    // Get data from localStorage
    const localData = JSON.parse(localStorage.getItem(localStorageKey) || '[]');
    if (!localData || localData.length === 0) return;
    
    // First ensure user exists if we're dealing with user-related data
    const username = localStorage.getItem('user_name');
    if (username && ['daily_points', 'monthly_points', 'quiz_answers'].includes(tableName)) {
      await ensureUserExists(username);
    }
    
    console.log(`Syncing ${localData.length} items from ${localStorageKey} to ${tableName}...`);
    
    // For each item in localStorage, upsert to Supabase
    for (const item of localData) {
      const dataToInsert = transform ? transform(item) : item;
      
      const { error } = await supabase
        .from(tableName as TableName)
        .upsert(dataToInsert, { onConflict: 'id' });
        
      if (error) {
        console.error(`Error syncing data to ${tableName}:`, error);
      }
    }
    
    console.log(`Data sync to ${tableName} completed`);
  } catch (err) {
    console.error(`Failed to sync ${localStorageKey} to Supabase:`, err);
  }
};

// Helper function to get data from Supabase and update localStorage
export const fetchDataFromSupabase = async (
  tableName: string, 
  localStorageKey: string,
  transform?: (item: any) => any,
  filters?: Record<string, any>
) => {
  try {
    // Cast to any to prevent TypeScript from getting stuck in recursive types
    let query = supabase
      .from(tableName as TableName)
      .select('*') as any;
    
    // Apply additional filters if provided
    if (filters) {
      Object.entries(filters).forEach(([key, value]) => {
        query = query.eq(key, value);
      });
    }
    
    // Order by created_at if available
    query = query.order('created_at', { ascending: false });
    
    const { data, error } = await query;
      
    if (error) {
      console.error(`Error fetching data from ${tableName}:`, error);
      return null;
    }
    
    if (data && data.length > 0) {
      const transformedData = transform ? data.map(transform) : data;
      localStorage.setItem(localStorageKey, JSON.stringify(transformedData));
      console.log(`Updated ${localStorageKey} with ${data.length} items from Supabase`);
      return transformedData;
    }
  } catch (err) {
    console.error(`Failed to fetch data from ${tableName}:`, err);
  }
  
  return null;
};

// Function to sync user points between localStorage and Supabase
export const syncUserPoints = async (username: string, points: number) => {
  try {
    if (!username) return;
    
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('username', username)
      .maybeSingle();
      
    if (profile) {
      // Update the points in the profile
      const { error } = await supabase
        .from('profiles')
        .update({ points, updated_at: new Date().toISOString() })
        .eq('id', profile.id);
        
      if (error) {
        console.error('Error updating user points:', error);
      } else {
        console.log(`Updated points for ${username} to ${points}`);
      }
    } else {
      // Create profile if it doesn't exist
      await ensureUserExists(username);
    }
  } catch (err) {
    console.error('Failed to sync user points:', err);
  }
};

// Helper function to sync daily and monthly points
export const syncPointsData = async (username: string) => {
  try {
    if (!username) return;
    
    // Get user profile
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('username', username)
      .maybeSingle();
      
    if (!profile) {
      console.log('No profile found for', username);
      return;
    }
    
    // Sync daily points
    const dailyPoints = JSON.parse(localStorage.getItem('daily_points') || '{}');
    for (const [date, points] of Object.entries(dailyPoints)) {
      const { error } = await supabase
        .from('daily_points')
        .upsert({
          user_id: profile.id,
          date: date,
          points: points as number
        }, { onConflict: 'user_id,date' });
        
      if (error) {
        console.error(`Error syncing daily points for ${date}:`, error);
      }
    }
    
    // Sync monthly points
    const monthlyPoints = JSON.parse(localStorage.getItem('monthly_points') || '{}');
    for (const [yearMonth, points] of Object.entries(monthlyPoints)) {
      const { error } = await supabase
        .from('monthly_points')
        .upsert({
          user_id: profile.id,
          year_month: yearMonth,
          points: points as number
        }, { onConflict: 'user_id,year_month' });
        
      if (error) {
        console.error(`Error syncing monthly points for ${yearMonth}:`, error);
      }
    }
    
    console.log('Synced points data for', username);
  } catch (err) {
    console.error('Failed to sync points data:', err);
  }
};

// New: Function to sync quiz answers to Supabase database
export const syncQuizAnswersToSupabase = async (username: string) => {
  try {
    if (!username) return;
    
    // Get user profile
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('username', username)
      .maybeSingle();
      
    if (!profile) {
      console.log('No profile found for', username);
      return;
    }
    
    // Get completed questions from localStorage
    const completedQuestions = JSON.parse(localStorage.getItem('quiz_app_user_quiz_history') || '[]');
    
    if (completedQuestions.length === 0) {
      console.log('No quiz answers to sync');
      return;
    }
    
    console.log(`Syncing ${completedQuestions.length} quiz answers for ${username}`);
    
    // For each answered question, create a record in Supabase
    for (const answer of completedQuestions) {
      const { error } = await supabase
        .from('quiz_answers')
        .upsert({
          id: answer.id || crypto.randomUUID(),
          user_id: profile.id,
          question_id: answer.questionId,
          user_answer: answer.selectedOption,
          is_correct: answer.isCorrect,
          points_earned: answer.pointsEarned || 0,
          answered_at: answer.timestamp || new Date().toISOString()
        }, { onConflict: 'id' });
        
      if (error) {
        console.error('Error syncing quiz answer:', error);
      }
    }
    
    console.log('Quiz answers sync completed');
  } catch (err) {
    console.error('Failed to sync quiz answers:', err);
  }
};

// New: Function to fetch quiz answers from Supabase to localStorage
export const fetchQuizAnswersFromSupabase = async (username: string) => {
  try {
    if (!username) return;
    
    // Get user profile
    const { data: profile } = await supabase
      .from('profiles')
      .select('*')
      .eq('username', username)
      .maybeSingle();
      
    if (!profile) {
      console.log('No profile found for', username);
      return;
    }
    
    // Get quiz answers from Supabase
    const { data, error } = await supabase
      .from('quiz_answers')
      .select('*, quiz_questions(id, question, options, correct_answer, category, difficulty)')
      .eq('user_id', profile.id)
      .order('answered_at', { ascending: false });
      
    if (error) {
      console.error('Error fetching quiz answers:', error);
      return;
    }
    
    if (data && data.length > 0) {
      // Transform data to match localStorage structure
      const transformedData = data.map(item => ({
        id: item.id,
        questionId: item.question_id,
        selectedOption: item.user_answer,
        isCorrect: item.is_correct,
        pointsEarned: item.points_earned || 0,
        timestamp: item.answered_at,
        question: item.quiz_questions?.question || '',
        options: item.quiz_questions?.options || [],
        correctAnswer: item.quiz_questions?.correct_answer || '',
        category: item.quiz_questions?.category || '',
        difficulty: item.quiz_questions?.difficulty || 'easy'
      }));
      
      localStorage.setItem('quiz_app_user_quiz_history', JSON.stringify(transformedData));
      console.log(`Updated quiz history with ${data.length} answers from Supabase`);
    }
  } catch (err) {
    console.error('Failed to fetch quiz answers:', err);
  }
};

// New: Helper function to sync quiz questions between Supabase and local storage
export const syncQuizQuestionsToSupabase = async () => {
  try {
    console.log('Starting two-way sync of quiz questions');
    
    const { data: existingQuestions, error: fetchError } = await supabase
      .from('quiz_questions')
      .select('id, question, options, correct_answer, difficulty, category, explanation, active, created_at');
      
    if (fetchError) {
      throw fetchError;
    }
    
    // Import quiz questions from utils
    const { quizQuestions } = await import('@/utils/quizData');
    
    const supabaseQuestionsMap = new Map();
    if (existingQuestions && existingQuestions.length > 0) {
      existingQuestions.forEach(q => {
        supabaseQuestionsMap.set(q.id, q);
      });
    }
    
    const localQuestions = [...quizQuestions];
    const localQuestionsMap = new Map();
    localQuestions.forEach(q => {
      localQuestionsMap.set(q.id, q);
    });
    
    const questionsToInsert = [];
    for (const localQ of localQuestions) {
      if (!supabaseQuestionsMap.has(localQ.id)) {
        questionsToInsert.push({
          id: localQ.id,
          question: localQ.question,
          options: localQ.options,
          correct_answer: localQ.correctAnswer,
          difficulty: localQ.difficulty,
          category: localQ.category,
          explanation: localQ.explanation || ''
        });
      }
    }
    
    if (questionsToInsert.length > 0) {
      console.log(`Inserting ${questionsToInsert.length} new questions to Supabase`);
      
      const BATCH_SIZE = 50;
      for (let i = 0; i < questionsToInsert.length; i += BATCH_SIZE) {
        const batch = questionsToInsert.slice(i, i + BATCH_SIZE);
        const { error } = await supabase
          .from('quiz_questions')
          .insert(batch);
          
        if (error) {
          console.error('Error syncing batch:', error);
        }
      }
    } else {
      console.log('No new local questions to add to Supabase');
    }
    
    const newLocalQuestions = [];
    if (existingQuestions) {
      for (const supabaseQ of existingQuestions) {
        if (!localQuestionsMap.has(supabaseQ.id) && supabaseQ.active !== false) {
          newLocalQuestions.push({
            id: supabaseQ.id,
            question: supabaseQ.question,
            options: Array.isArray(supabaseQ.options) ? supabaseQ.options : [],
            correctAnswer: supabaseQ.correct_answer,
            difficulty: (supabaseQ.difficulty as 'easy' | 'medium' | 'hard') || 'easy',
            category: supabaseQ.category || 'General Knowledge',
            explanation: supabaseQ.explanation || ''
          });
        }
      }
      
      if (newLocalQuestions.length > 0) {
        console.log(`Adding ${newLocalQuestions.length} new questions from Supabase to local`);
        const allQuestions = [...quizQuestions, ...newLocalQuestions];
        localStorage.setItem('quiz_app_questions_cache', JSON.stringify(allQuestions));
        
        console.log('Updated local questions cache. Reload the app to see new questions.');
      } else {
        console.log('No new questions from Supabase to add locally');
      }
    }
    
    console.log('Quiz questions sync completed');
    return {
      supabaseCount: existingQuestions?.length || 0,
      localCount: localQuestions.length,
      addedToSupabase: questionsToInsert.length,
      addedToLocal: newLocalQuestions.length
    };
  } catch (error) {
    console.error('Error syncing quiz questions:', error);
    throw error;
  }
};

// New: Helper function to sync ad slots from Supabase to localStorage
export const syncAdSlotsToLocal = async () => {
  try {
    const { data, error } = await supabase
      .from('ad_slots')
      .select('*')
      .eq('active', true);
      
    if (error) {
      throw error;
    }
    
    if (data) {
      localStorage.setItem('quiz_app_ad_slots', JSON.stringify(data));
    }
  } catch (error) {
    console.error('Error syncing ad slots:', error);
  }
};

// Extended function to sync all types of data
export const syncAllDataToSupabase = async () => {
  try {
    // Get current user
    const username = localStorage.getItem('user_name');
    if (!username) {
      console.log('No user logged in, skipping sync');
      return;
    }
    
    // Ensure questions are synced first
    await syncQuizQuestionsToSupabase();
    
    // Sync user points
    const points = parseInt(localStorage.getItem('user_points') || '0');
    await syncUserPoints(username, points);
    
    // Sync daily and monthly points
    await syncPointsData(username);
    
    // Sync quiz answers
    await syncQuizAnswersToSupabase(username);
    
    // Fetch ad slots to local
    await syncAdSlotsToLocal();
    
    console.log('All data synced successfully');
  } catch (error) {
    console.error('Error syncing all data:', error);
  }
};

// Helper function to sync from Supabase to localStorage
export const fetchAllDataFromSupabase = async () => {
  try {
    // Get current user
    const username = localStorage.getItem('user_name');
    if (!username) {
      console.log('No user logged in, skipping fetch');
      return;
    }
    
    // Fetch ad slots
    await syncAdSlotsToLocal();
    
    // Fetch quiz answers
    await fetchQuizAnswersFromSupabase(username);
    
    console.log('All data fetched successfully');
  } catch (error) {
    console.error('Error fetching all data:', error);
  }
};
